<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>11.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Portable.System.DateTimeOnly" Version="9.0.2" />
    <PackageReference Include="Portable.System.DateTimeOnly.Json" Version="9.1.1" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>

</Project>
